### ISSUE TITLE
DB의 employee와 company 테이블에서 jobId 컬럼을 삭제하여야 합니다.

### ISSUE THREAD

**Issue by mb6282** [jinsa004/miniproject#37]
DB의 employee와 company 테이블에서 jobId를 받을 필요가 없습니다. 해당 컬럼을 삭제하여야 코드가 정상 작동합니다.
employee, company 엔티티의 jobId는 다른 기능에서 사용하는 엔티티가 아닌 패러미터이므로 남겨두어야 합니다.

**Comment by jinsa004** [comment]
db 테이블에서 삭제하도록 하고 entity에는 entity가 아닌 필드로 해서 지정해두겠습니다

**Comment by jinsa004** [comment]
README 테이블 설계에서 삭제했고 엔티티에도 entity가 아닌 필드로 지정해두었습니다
