### ISSUE TITLE
기업 매칭리스트 이력서 보기 jobName이 나오도록 쿼리문을 수정해야 합니다.

### ISSUE THREAD

**Issue by mb6282** [jinsa004/miniproject#45]
- 기업 매칭리스트 이력서 보기 jobName이 나오도록 쿼리문을 수정해야 합니다.
- 가능하다면 기업과 구직자 매칭리스트 쿼리문 모두 수정하는 것이 필요해 보입니다.

**Comment by jinsa004** [comment]
쿼리문 새로 짜봤는데
        SELECT *
        FROM (SELECT r.resume_id, r.resume_title, e.employee_name, r.job_id, r.career_period
        FROM resume r
        INNER JOIN employee e
        ON r.employee_id = e.employee_id) re
        INNER JOIN (SELECT j.job_name, j.job_id
        FROM co_check c
        INNER JOIN job j
        ON c.job_id = j.job_id
        WHERE c.company_id = #{companyId}
        GROUP BY c.job_id) cj
        ON re.job_id = cj.job_id
        GROUP BY cj.job_id
로 하면 제대로 불러와지는 거 같습니다
